FROM jpdeplaix/opam2-alpine:arm64
WORKDIR /home/opam/opam-repository
RUN git pull origin master && opam admin cache -n
# The next command will be executed at startup then once a day
CMD ["watch","-n","86400","git pull origin master && opam admin cache -n"]
