version: '2.1'
volumes:
  session_data:
services:
  ci:
    restart: always
    build: .
    entrypoint: /home/opam/.opam/4.05.0/bin/${CI_BINARY}
    command: --metadata-store tcp:datakit:5640 --web-ui=https://${CI_DOMAIN_NAME}/ --sessions-backend=redis://redis
    memswap_limit: -1
    ports:
     - "443:8443"
    volumes:
     - ./data/ci/repos:/data/repos
     - ./data/ci/secrets:/secrets
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - datakit
     - redis
  datakit:
    restart: always
    image: jpdeplaix/datakit-db
    user: "root"
    volumes:
      - ./data/datakit/data:/data
      - ./data/datakit/_ssh:/root/.ssh
    command: --git /data --listen-9p tcp://0.0.0.0:5640
    memswap_limit: -1
  bridge:
    restart: always
    image: jpdeplaix/datakit-github-bridge
    command: --datakit tcp://datakit:5640 -v -c "*:r,status[ci/datakit]:x,webhook:rw" --webhook http://${CI_DOMAIN_NAME}:8100
    memswap_limit: -1
    ports:
     - "8100:8100"
    volumes:
      - ./data/bridge:/run/secrets
    depends_on:
     - datakit
  redis:
    restart: always
    image: redis
    command: redis-server --save 60 1
    memswap_limit: -1
    volumes:
      - session_data:/data
